language: python
python:
  - "3.5"
cache: pip
install:
  - pip install awscli
script:
    -make lab2/index.html
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: git-to-amazon-s3-hathohu-outputbucket-ncocjced8fab
  skip_cleanup: true