language: python
python:
  - "3.5"
cache: pip
install:
  - pip install awscli
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: git-to-amazon-s3-hathohu-outputbucket-ncocjced8fab
  skip_cleanup: true